GET http://localhost:4000/ping

###
POST http://localhost:4000/professionals/signin

###
POST http://localhost:4000/professionals/register
Content-Type: application/json

{
  "name": "Cláudio Cardoso",
  "email": "claudio.c.lima@hotmail.com",
  "password": "262011",
  "phone": "(83) 999126797",
  "barber": false
}
